-- Activity Network v0.2.6 - Notifications & History
-- Run after v0.2.5. Adds in-app notifications, activity event log,
-- immutable per-user activity history snapshots, and GPS route history.

create extension if not exists pgcrypto;

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text not null default '',
  category text not null default 'activities' check (category in ('activities','groups','messages','important')),
  priority text not null default 'normal' check (priority in ('normal','important','critical')),
  route text,
  entity_type text,
  entity_id uuid,
  created_at timestamptz not null default now(),
  read_at timestamptz
);
create index if not exists notifications_user_created_idx on public.notifications(user_id,created_at desc);
create index if not exists notifications_user_unread_idx on public.notifications(user_id,read_at) where read_at is null;

create table if not exists public.activity_events (
  id uuid primary key default gen_random_uuid(),
  activity_id uuid not null references public.activities(id) on delete cascade,
  event_type text not null,
  actor_user_id uuid references public.profiles(id) on delete set null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists activity_events_activity_created_idx on public.activity_events(activity_id,created_at);

create table if not exists public.activity_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  activity_id uuid references public.activities(id) on delete set null,
  title text not null,
  activity_type text not null,
  role text not null check (role in ('leader','sweep','participant')),
  started_at timestamptz,
  finished_at timestamptz not null,
  duration_minutes integer not null default 0 check (duration_minutes >= 0),
  distance_km numeric(10,2) not null default 0 check (distance_km >= 0),
  participant_count integer not null default 0 check (participant_count >= 0),
  route_label text not null default 'Rute ikke lagret',
  route_saved boolean not null default false,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(user_id, activity_id)
);
create index if not exists activity_history_user_finished_idx on public.activity_history(user_id,finished_at desc);

create table if not exists public.activity_route_history (
  id bigint generated by default as identity primary key,
  history_id uuid references public.activity_history(id) on delete cascade,
  activity_id uuid references public.activities(id) on delete set null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  sequence bigint not null,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy_m double precision not null default 0,
  heading_deg double precision,
  speed_mps double precision,
  recorded_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique(activity_id,user_id,sequence)
);
create index if not exists activity_route_history_history_recorded_idx on public.activity_route_history(history_id,recorded_at);
create index if not exists activity_route_history_activity_user_idx on public.activity_route_history(activity_id,user_id,recorded_at);

-- Generic helper. Writes are server-generated; clients never insert notifications directly.
create or replace function public.create_notification(
  p_user_id uuid,
  p_title text,
  p_body text,
  p_category text default 'activities',
  p_priority text default 'normal',
  p_route text default null,
  p_entity_type text default null,
  p_entity_id uuid default null
) returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid;
begin
  insert into public.notifications(user_id,title,body,category,priority,route,entity_type,entity_id)
  values(p_user_id,p_title,p_body,p_category,p_priority,p_route,p_entity_type,p_entity_id)
  returning id into v_id;
  return v_id;
end; $$;
revoke all on function public.create_notification(uuid,text,text,text,text,text,text,uuid) from public;

create or replace function public.log_activity_created()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.activity_events(activity_id,event_type,actor_user_id,data)
  values(new.id,'activity_created',new.created_by,jsonb_build_object('status',new.status,'starts_at',new.starts_at));
  return new;
end; $$;
drop trigger if exists activity_event_created on public.activities;
create trigger activity_event_created after insert on public.activities
for each row execute procedure public.log_activity_created();

create or replace function public.log_activity_change_and_notify()
returns trigger language plpgsql security definer set search_path=public as $$
declare r record; v_title text;
begin
  if new.status is distinct from old.status then
    insert into public.activity_events(activity_id,event_type,actor_user_id,data)
    values(new.id,'status_changed',auth.uid(),jsonb_build_object('from',old.status,'to',new.status));
    v_title := case new.status
      when 'gathering' then 'Samling har startet'
      when 'active' then 'Aktiviteten har startet'
      when 'paused' then 'Aktiviteten er satt på pause'
      when 'finished' then 'Aktiviteten er avsluttet'
      when 'cancelled' then 'Aktiviteten er avlyst'
      else 'Aktivitetsstatus endret' end;
    for r in select user_id from public.activity_participants
      where activity_id=new.id and status in ('approved','active') and user_id is distinct from auth.uid()
    loop
      perform public.create_notification(r.user_id,v_title,new.title,'activities',
        case when new.status='cancelled' then 'important' else 'normal' end,
        '/activity/'||new.id::text,'activity',new.id);
    end loop;
  end if;

  if new.meeting_point is distinct from old.meeting_point then
    insert into public.activity_events(activity_id,event_type,actor_user_id,data)
    values(new.id,'meeting_point_changed',auth.uid(),jsonb_build_object('from',old.meeting_point,'to',new.meeting_point));
    for r in select user_id from public.activity_participants
      where activity_id=new.id and status in ('approved','active') and user_id is distinct from auth.uid()
    loop
      perform public.create_notification(r.user_id,'Møtepunkt endret',new.title||' · '||new.meeting_point,'activities','important','/activity/'||new.id::text,'activity',new.id);
    end loop;
  end if;
  return new;
end; $$;
drop trigger if exists activity_change_event_notify on public.activities;
create trigger activity_change_event_notify after update of status,meeting_point on public.activities
for each row execute procedure public.log_activity_change_and_notify();

create or replace function public.activity_participant_event_notify()
returns trigger language plpgsql security definer set search_path=public as $$
declare r record; v_title text;
begin
  if tg_op='INSERT' then
    insert into public.activity_events(activity_id,event_type,actor_user_id,data)
    values(new.activity_id,'participant_'||new.status,new.user_id,jsonb_build_object('role',new.role));
    if new.status='requested' then
      for r in select user_id from public.activity_participants
        where activity_id=new.activity_id and role='leader' and status in ('approved','active')
      loop
        if r.user_id <> new.user_id then
          perform public.create_notification(r.user_id,'Ny forespørsel om å bli med','En bruker ønsker å bli med på aktiviteten.','activities','normal','/activity/'||new.activity_id::text,'activity',new.activity_id);
        end if;
      end loop;
    end if;
  elsif new.status is distinct from old.status then
    insert into public.activity_events(activity_id,event_type,actor_user_id,data)
    values(new.activity_id,'participant_status_changed',auth.uid(),jsonb_build_object('user_id',new.user_id,'from',old.status,'to',new.status,'role',new.role));
    if new.status in ('approved','active') and old.status not in ('approved','active') then
      perform public.create_notification(new.user_id,'Forespørselen din ble godkjent','Du er nå med på aktiviteten.','activities','normal','/activity/'||new.activity_id::text,'activity',new.activity_id);
    elsif new.status in ('rejected','removed') and old.status is distinct from new.status then
      perform public.create_notification(new.user_id,'Deltakelse oppdatert','Du er ikke lenger registrert som deltaker.','activities','important','/activity/'||new.activity_id::text,'activity',new.activity_id);
    end if;
  end if;
  return new;
end; $$;
drop trigger if exists activity_participant_event_notify_trigger on public.activity_participants;
create trigger activity_participant_event_notify_trigger
after insert or update of status on public.activity_participants
for each row execute procedure public.activity_participant_event_notify();


create table if not exists public.live_route_preferences (
  activity_id uuid not null references public.activities(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key(activity_id,user_id)
);

create or replace function public.set_route_history_preference(p_activity_id uuid, p_enabled boolean)
returns void language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  if not public.is_activity_participant(p_activity_id,auth.uid()) then raise exception 'participant_required'; end if;
  insert into public.live_route_preferences(activity_id,user_id,enabled,updated_at)
  values(p_activity_id,auth.uid(),p_enabled,now())
  on conflict(activity_id,user_id) do update set enabled=excluded.enabled, updated_at=now();
end; $$;
grant execute on function public.set_route_history_preference(uuid,boolean) to authenticated;

-- Save every accepted live position as route history. The live table itself only keeps the latest point.
create or replace function public.capture_live_route_point()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if not new.sharing then return new; end if;
  if tg_op='UPDATE' and new.sequence is not distinct from old.sequence then return new; end if;
  if not coalesce((select enabled from public.live_route_preferences where activity_id=new.activity_id and user_id=new.user_id), true) then return new; end if;

  insert into public.activity_route_history(activity_id,user_id,sequence,latitude,longitude,accuracy_m,heading_deg,speed_mps,recorded_at)
  values(new.activity_id,new.user_id,new.sequence,new.latitude,new.longitude,new.accuracy_m,new.heading_deg,new.speed_mps,new.recorded_at)
  on conflict(activity_id,user_id,sequence) do nothing;
  return new;
end; $$;
drop trigger if exists live_participants_capture_route on public.live_participants;
create trigger live_participants_capture_route
after insert or update of sequence on public.live_participants
for each row execute procedure public.capture_live_route_point();

-- Snapshot one immutable history row per confirmed participant when a trip finishes.
create or replace function public.snapshot_finished_activity()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  r record;
  v_start timestamptz;
  v_duration integer;
  v_count integer;
  v_history_id uuid;
  v_has_route boolean;
begin
  if new.status='finished' and old.status is distinct from 'finished' then
    select coalesce(ls.started_at,new.starts_at) into v_start from public.live_sessions ls where ls.activity_id=new.id;
    v_start := coalesce(v_start,new.starts_at,new.created_at);
    v_duration := greatest(0, floor(extract(epoch from (coalesce(new.finished_at,now()) - v_start))/60)::integer);
    select count(*)::integer into v_count from public.activity_participants where activity_id=new.id and status in ('approved','active');

    for r in select user_id,role from public.activity_participants where activity_id=new.id and status in ('approved','active') loop
      select exists(select 1 from public.activity_route_history where activity_id=new.id and user_id=r.user_id) into v_has_route;
      insert into public.activity_history(user_id,activity_id,title,activity_type,role,started_at,finished_at,duration_minutes,distance_km,participant_count,route_label,route_saved,summary)
      values(r.user_id,new.id,new.title,new.activity_type,r.role,v_start,coalesce(new.finished_at,now()),v_duration,new.distance_km,v_count,new.route_label,v_has_route,
        jsonb_build_object('meeting_point',new.meeting_point,'pace',new.pace,'surface',new.surface))
      on conflict(user_id,activity_id) do update set
        title=excluded.title, activity_type=excluded.activity_type, role=excluded.role,
        started_at=excluded.started_at, finished_at=excluded.finished_at, duration_minutes=excluded.duration_minutes,
        distance_km=excluded.distance_km, participant_count=excluded.participant_count,
        route_label=excluded.route_label, route_saved=excluded.route_saved, summary=excluded.summary
      returning id into v_history_id;
      update public.activity_route_history set history_id=v_history_id where activity_id=new.id and user_id=r.user_id and history_id is null;
      perform public.create_notification(r.user_id,'Aktivitet lagret i historikk',new.title,'activities','normal','/history/'||v_history_id::text,'history',v_history_id);
    end loop;
  end if;
  return new;
end; $$;
drop trigger if exists activity_snapshot_finished on public.activities;
create trigger activity_snapshot_finished after update of status on public.activities
for each row execute procedure public.snapshot_finished_activity();

-- Group membership notifications.
create or replace function public.group_member_notify()
returns trigger language plpgsql security definer set search_path=public as $$
declare r record; v_name text;
begin
  select name into v_name from public.groups where id=new.group_id;
  if tg_op='INSERT' and new.status='requested' then
    for r in select user_id from public.group_members where group_id=new.group_id and role in ('owner','admin') and status='active' loop
      if r.user_id <> new.user_id then
        perform public.create_notification(r.user_id,'Ny gruppeforespørsel',coalesce(v_name,'Gruppe'),'groups','normal','/group/'||new.group_id::text||'/admin','group',new.group_id);
      end if;
    end loop;
  elsif tg_op='UPDATE' and new.status is distinct from old.status then
    if new.status='active' and old.status <> 'active' then
      perform public.create_notification(new.user_id,'Du er medlem',coalesce(v_name,'Gruppe'),'groups','normal','/group/'||new.group_id::text,'group',new.group_id);
    elsif new.status='removed' then
      perform public.create_notification(new.user_id,'Gruppemedlemskap avsluttet',coalesce(v_name,'Gruppe'),'groups','important',null,'group',new.group_id);
    end if;
  end if;
  return new;
end; $$;
drop trigger if exists group_member_notification_trigger on public.group_members;
create trigger group_member_notification_trigger after insert or update of status on public.group_members
for each row execute procedure public.group_member_notify();

-- Chat notifications. Realtime chat remains the primary foreground experience;
-- this produces in-app notification records for other members.
create or replace function public.message_notify_members()
returns trigger language plpgsql security definer set search_path=public as $$
declare r record; c public.chats%rowtype; v_route text; v_category text; v_priority text;
begin
  select * into c from public.chats where id=new.chat_id;
  v_route := case when c.chat_type='activity' then '/activity/'||c.activity_id::text||'/chat' else '/group/'||c.group_id::text||'/chat' end;
  v_category := case when new.important then 'important' else 'messages' end;
  v_priority := case when new.important then 'critical' else 'normal' end;
  for r in select user_id from public.chat_members where chat_id=new.chat_id and user_id is distinct from new.sender_id loop
    perform public.create_notification(r.user_id,case when new.important then 'Viktig melding' else 'Ny melding' end,
      left(new.body,220),v_category,v_priority,v_route,c.chat_type,coalesce(c.activity_id,c.group_id));
  end loop;
  return new;
end; $$;
drop trigger if exists message_notification_trigger on public.messages;
create trigger message_notification_trigger after insert on public.messages
for each row when (new.message_type <> 'system') execute procedure public.message_notify_members();


-- Backfill already-finished real activities from earlier milestones. Route points cannot be reconstructed retroactively.
insert into public.activity_history(user_id,activity_id,title,activity_type,role,started_at,finished_at,duration_minutes,distance_km,participant_count,route_label,route_saved,summary)
select ap.user_id,a.id,a.title,a.activity_type,ap.role,a.starts_at,coalesce(a.finished_at,a.updated_at),
       greatest(0,floor(extract(epoch from (coalesce(a.finished_at,a.updated_at)-a.starts_at))/60)::integer),
       a.distance_km,
       (select count(*)::integer from public.activity_participants x where x.activity_id=a.id and x.status in ('approved','active')),
       a.route_label,false,jsonb_build_object('meeting_point',a.meeting_point,'pace',a.pace,'surface',a.surface)
from public.activities a
join public.activity_participants ap on ap.activity_id=a.id and ap.status in ('approved','active')
where a.status='finished'
on conflict(user_id,activity_id) do nothing;

-- RLS
alter table public.notifications enable row level security;
alter table public.activity_events enable row level security;
alter table public.activity_history enable row level security;
alter table public.activity_route_history enable row level security;
alter table public.live_route_preferences enable row level security;

drop policy if exists notifications_select_own on public.notifications;
create policy notifications_select_own on public.notifications for select to authenticated using (user_id=auth.uid());
drop policy if exists notifications_update_own on public.notifications;
create policy notifications_update_own on public.notifications for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
drop policy if exists notifications_delete_own on public.notifications;
create policy notifications_delete_own on public.notifications for delete to authenticated using (user_id=auth.uid());

drop policy if exists activity_events_select_participants on public.activity_events;
create policy activity_events_select_participants on public.activity_events for select to authenticated using (public.is_activity_participant(activity_id,auth.uid()) or public.is_activity_leader(activity_id,auth.uid()));

drop policy if exists activity_history_select_own on public.activity_history;
create policy activity_history_select_own on public.activity_history for select to authenticated using (user_id=auth.uid());
drop policy if exists activity_history_delete_own on public.activity_history;
create policy activity_history_delete_own on public.activity_history for delete to authenticated using (user_id=auth.uid());


drop policy if exists live_route_preferences_select_own on public.live_route_preferences;
create policy live_route_preferences_select_own on public.live_route_preferences for select to authenticated using (user_id=auth.uid());

drop policy if exists activity_route_history_select_own on public.activity_route_history;
create policy activity_route_history_select_own on public.activity_route_history for select to authenticated using (user_id=auth.uid());

-- No client inserts to event/history/route tables. Notifications may only be marked read/deleted by owner.
grant select,delete on public.notifications to authenticated;
grant update(read_at) on public.notifications to authenticated;
revoke insert on public.notifications from authenticated;
grant select on public.activity_events to authenticated;
revoke insert,update,delete on public.activity_events from authenticated;
grant select,delete on public.activity_history to authenticated;
revoke insert,update on public.activity_history from authenticated;
grant select on public.activity_route_history to authenticated;
grant select on public.live_route_preferences to authenticated;
revoke insert,update,delete on public.live_route_preferences from authenticated;
revoke insert,update,delete on public.activity_route_history from authenticated;

-- In-app notifications update live.
do $$ begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null;
end $$;
